package dev.luaxide.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme — indigo/blue primary, teal secondary
val md_primary = Color(0xFF185FA5)
val md_onPrimary = Color(0xFFFFFFFF)
val md_primaryContainer = Color(0xFFD4E3FF)
val md_onPrimaryContainer = Color(0xFF001D36)
val md_secondary = Color(0xFF0F6E56)
val md_onSecondary = Color(0xFFFFFFFF)
val md_secondaryContainer = Color(0xFF9FE1CB)
val md_onSecondaryContainer = Color(0xFF003829)
val md_tertiary = Color(0xFF7F5CDD)
val md_onTertiary = Color(0xFFFFFFFF)
val md_background = Color(0xFFFDFBFF)
val md_onBackground = Color(0xFF1A1C1E)
val md_surface = Color(0xFFFDFBFF)
val md_onSurface = Color(0xFF1A1C1E)
val md_surfaceVariant = Color(0xFFDFE2EB)
val md_onSurfaceVariant = Color(0xFF43474E)
val md_outline = Color(0xFF73777F)
val md_outlineVariant = Color(0xFFC3C6CF)
val md_error = Color(0xFFBA1A1A)
val md_onError = Color(0xFFFFFFFF)

// Dark scheme
val md_primary_d = Color(0xFFA2C9FF)
val md_onPrimary_d = Color(0xFF003258)
val md_primaryContainer_d = Color(0xFF00497D)
val md_onPrimaryContainer_d = Color(0xFFD4E3FF)
val md_secondary_d = Color(0xFF83D6AF)
val md_onSecondary_d = Color(0xFF003929)
val md_secondaryContainer_d = Color(0xFF00513B)
val md_onSecondaryContainer_d = Color(0xFF9FE1CB)
val md_tertiary_d = Color(0xFFC9BFFF)
val md_onTertiary_d = Color(0xFF311F8A)
val md_background_d = Color(0xFF1A1C1E)
val md_onBackground_d = Color(0xFFE3E2E6)
val md_surface_d = Color(0xFF1A1C1E)
val md_onSurface_d = Color(0xFFE3E2E6)
val md_surfaceVariant_d = Color(0xFF43474E)
val md_onSurfaceVariant_d = Color(0xFFC3C6CF)
val md_outline_d = Color(0xFF8D9199)
val md_outlineVariant_d = Color(0xFF43474E)
val md_error_d = Color(0xFFFFB4AB)
val md_onError_d = Color(0xFF690005)
